services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: purr-case-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - merchant_id=${merchant_id}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: purr-case-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
